name: labyrinth
description: "-"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  svg_path_parser: ^1.1.1 # TODO: Consider using flame_svg instead?
  cupertino_icons: ^1.0.8
  flame: ^1.21.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  sensors_plus: ^6.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  logger: ^2.4.0
  sqflite: ^2.4.0
  path: ^1.9.0
  animated_background: ^2.0.0
  shared_preferences: ^2.3.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/bgm/
    - assets/audio/sfx/
    - assets/icons/
    - assets/images/
    - assets/lang/
    - assets/levels/
